---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng
  name: rng-deploy
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: rng
  templete:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng-container
        image: brahamirabah94/rng:1.0.1
        ports:
        - conatinerPort: 80
